#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'jekyll'

USER_CONFIG  = "#{ENV['build_dir']}/static.json"

class StaticConfig

  def initialize(json_file)
    @json = {}
    @json = JSON.parse(File.read(json_file)) if File.exist?(json_file)
    @json['jekyll'] ||= {
      'source' => ENV['build_dir']
    }
    @json['root'] ||= 'public_html/'
  end

  def jekyll_options
    @json['jekyll'].merge({
      'destination' => "#{ENV['build_dir']}/#{@json['root']}"
    })
  end
end

config = StaticConfig.new(USER_CONFIG)
puts config.jekyll_options.inspect
site = ::Jekyll::Site.new(::Jekyll.configuration(config.jekyll_options))
site.process
